id: P006653
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20415
  title: ཤམ་བྷ་ལའི་ཅོང་སྒྲ།
  author: ''
  volumes:
    18b1b5cfc847402b8ad657cf5d2fb063:
      image_group_id: I1KG12352
      title: ''
      volume_number: 1
      total_pages: 318
      base_file: v001.txt
