id: I10663847
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T18:26:56+00:00'
last_modified: '2022-06-08T05:56:20.055550+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20415
  title: ཤམ་བྷ་ལའི་ཅོང་སྒྲ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '8155':
      image_group_id: I1KG12352
      title: ''
      total_pages: 318
      order: 1
      base_file: 8155.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
